# Default values for py-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: ""
  tag: ""
  pullPolicy: Always

replicaCount: 1
resources: {}

config: {}
existingSecret: ""
secret: {}


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  rootEnabled: false
  annotations: {}
  # subdomain, for example `pyrepo.endergy.co`
  subdomain: "admin"
  # hosts, if empty use all hosts defined in lib
  hosts: []
