apiVersion: v2
name: py-repo
description: Deploys a python repository used as a custom pypi instance.
type: application

version: 0.1.0
appVersion: latest

# Chart dependencies
dependencies:
- name: endergy-lib
  version: 0.1.0
  repository: file://../endergy-lib
