# Default values for py-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: pypiserver/pypiserver
  pullPolicy: Always

fullnameOverride: ""
resources: {}
# htpasswd concatins password entries used for authenticating pyrepo access
htpasswd: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  # subdomain, for example `pyrepo.endergy.co`
  subdomain: "pyrepo"
  # hosts, if empty use all hosts defined in endergy-lib
  hosts: []
