{{- include "lib.ingress" . -}}

{{- $fullName := include "lib.common.fullname" . -}}
{{- $hosts := list "summn.co" -}}
{{- $svcPort := .Values.service.port -}}
{{- $subdomain := .Values.ingress.subdomain -}}
{{- range $hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName | quote }}
              servicePort: {{ $svcPort }}
{{- end -}}
