{{- include "lib.ingress" . -}}

{{- if .Values.ingress.noSubdomain -}}
{{- $fullName := include "lib.common.fullname" . -}}
{{- $hosts := .Values.lib.hosts -}}
{{- $svcPort := .Values.service.port -}}
{{- range $hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName | quote }}
              servicePort: {{ $svcPort }}
{{- end -}}
{{- end -}}
