{{- if (or .Release.IsInstall (or .Values.server.mailPassword .Values.server.sqlConnectionUri)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lib.common.fullname" . }}
type: Opaque
data:
  MAIL_USERNAME: {{ b64enc .Values.server.mailUsername | quote }}
  MAIL_PASSWORD: {{ b64enc (include "landing-page.server.mailPassword" .) | quote }}
  SQL_CONNECTION_URI: {{ b64enc (include "landing-page.server.sqlConnectionUri" .) | quote }}
{{- end -}}
