version: "3.7"
services:
  orchestrator:
    image: jaredhanson11/orchestrator
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../:/keystone"
      - "${HOME}/.ssh/:/root/.ssh/"
    labels:
      - traefik.enable=True
networks:
  default:
    external:
      name: endergy-network
