# Default values for py-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: jaredhanson11/endergy-landing-page-client
  pullPolicy: Always

replicaCount: 1
resources: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  # subdomain, for example `pyrepo.endergy.co`
  subdomain: "landing"
  # hosts, if empty use all hosts defined in lib
  hosts: []
