# Default values for py-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: jaredhanson11/summn-landing-page-client
  imageVersion: latest
  pullPolicy: Always

replicaCount: 1
resources: {}

service:
  type: ClusterIP
  port: 80

ingress:
  isRoot: false
  enabled: true
  annotations: {}
  # subdomain, for example `pyrepo.endergy.co`
  subdomain: "landing"
  # hosts, if empty use all hosts defined in lib
  hosts: []

server:
  image:
    repository: jaredhanson11/summn-landing-page-server
    imageVersion: latest
    pullPolicy: Always
  dbConnection:
    prefix: "postgresql://"
    passwordSecret:
      secretName: postgres-secrets
      keyName: postgresql-password
    user: postgres
    port: 5432
    host: postgresql.common
    name: summn_landing_page
