{{- if not .Values.job.cron.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  {{/* The following -revision will force rerun of new job every upgrade */}}
  name: {{ printf "%s-%d" (include "lib.common.fullname" .) .Release.Revision }}
  labels:
    {{- include "lib.common.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{  include "lib.common.selectorLabels" . | nindent 12 }}
    spec:
      containers:
        - name: "main-job"
          image: {{ printf "%s:%s" (required "Missing image.repository" .Values.image.repository) (required "Missing image.tag" .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.job.args }}
          args: {{ . }}
          {{- end }}
          env:
{{- include "lib.deploy.envConfigs" . | nindent 12 }}
{{- include "lib.deploy.envSecrets" . | nindent 12 }}
{{- include "lib.db.sqlalchemyDbUri" . | nindent 12 }}
      restartPolicy: {{ .Values.job.restartPolicy }}
{{- end -}}
