# Infrastructure like package registries, jenkins, etc.
# Infrastructure containers are exposed at 692* ports
version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
    - "${HOME}/.endergy-data/jenkins-home/:/var/jenkins_home/"

  docker-registry:
    image: registry:2
    volumes:
    - "${HOME}/.endergy-data/docker-registry/:/var/lib/registry/"

  python-repository:
    image: pypiserver/pypiserver:latest
    command: -P /data/.htpasswd /data/packages
    volumes:
    - "${HOME}/.endergy-data/python-repository/:/data/packages"
    configs:
    - source: pypipasswd.txt
      target: /data/.htpasswd

configs:
  pypipasswd.txt:
    external: true
