image:
  tag: 1.21.0-debian-10-r0

kubeVersion: 1.18

ingress:
  enabled: true
  hostname: goflok.com

serverBlock: |-
  server {
      listen       8080;
      listen  [::]:8080;
      server_name  localhost;
      # access_log  /var/log/nginx/host.access.log  main;
      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
          root   /usr/share/nginx/html;
      }
      location  /blog/ {
          # Already exist in ghost namespace
          proxy_pass http://ghost.ghost-dqmd6npm/blog/;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;

      }
      location / {
          proxy_pass   http://flok-landing-page-prod-webclient-app/;
      }
  }
