apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lib.common.fullname" . }}
  labels:
    {{- include "lib.common.labels" . | nindent 4 }}
data:
  config.py: |-
{{ index .Values "config.py" | nindent 4 }}
{{ with .Values.customLogfile }}
  logging.conf: |-
{{- . | nindent 4 }}
{{- end -}}
