{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamt-app.secretName" . }}
type: Opaque
data:
{{ range $key, $val := .Values.secret }}
  {{ $key }}: {{ required "Missing value." $val | b64enc }}
{{- end -}}
{{- end -}}
