{{- if .Release.IsInstall -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lib.common.fullname" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
{{- if and .Values.user .Values.password }}
  basic-auth-user: {{ b64enc .Values.user | quote }}
  basic-auth-pass: {{ b64enc .Values.password | quote }}
{{- else -}}
  {{- fail ".Values.user or .Values.password not set." -}}
{{- end -}}
{{- end -}}
