{{- if not .Release.IsUpgrade -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "endergy-lib.common.fullname" . }}
type: Opaque
data:
{{- if and .Values.user .Values.password }}
  basic-auth-user: {{ b64enc .Values.user | quote }}
  basic-auth-pass: {{ b64enc .Values.password | quote }}
{{- else -}}
  {{- fail ".Values.user or .Values.password not set." -}}
{{- end -}}
{{- end -}}