apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "endergy-lib.common.fullname" . }}
  labels:
    {{- include "endergy-lib.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "endergy-lib.common.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "endergy-lib.common.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "endergy-lib.common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STORAGE
              value: local
            - name: STORAGE_LOCAL_ROOTDIR
              value: /charts
            - name: DEBUG
              value: "1"
            - name: ALLOW_OVERWRITE
              value: "1"
            - name: BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "endergy-lib.common.fullname" . }}
                  key: basic-auth-user
            - name: BASIC_AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "endergy-lib.common.fullname" . }}
                  key: basic-auth-pass
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: helm-data
              mountPath: /charts
      initContainers:
      - name: helm-data-setup
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /charts"]
        volumeMounts:
        - name: helm-data
          mountPath: /charts
  volumeClaimTemplates:
    - metadata:
        name: helm-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
