apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "endergy-lib.common.fullname" . }}
  labels:
    {{- include "endergy-lib.common.labels" . | nindent 4 }}
data:
  .htpasswd: {{ .Values.htpasswd }}
