apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "py-repo.fullname" . }}
  labels:
    {{- include "py-repo.labels" . | nindent 4 }}
data:
  .htpasswd: "endergy-automation:{SHA}8v9akPd5PzHroQhtl/o6gfJb2Sg="
