apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "py-repo.fullname" . }}
  labels:
    {{- include "py-repo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "py-repo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "py-repo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PORT"
              value: "80"
            - name: "DB"
              value: {{ include "py-repo.dbUrl" . | quote }}
            - name: "PYPI_PROXY"
              value: {{ int .Values.enabledPypiProxy | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
