{{- if .Values.ingress.enabled -}}
{{- $fullName := include "py-repo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "py-repo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /py-repo
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
  {{- end }}
