apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "py-repo.fullname" . }}
  labels:
    {{- include "py-repo.labels" . | nindent 6 }}
  annotations:
    check-sum/py-repo.conf: {{ sha1sum (tpl (.Files.Get "files/py-repo.conf") .) }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "py-repo.fullname" . }}
  selector:
    matchLabels: {{- include "py-repo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "py-repo.selectorLabels" . | nindent 8 }}
    spec: 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/check
              port: http
          volumeMounts:
          - name: {{ include "py-repo.fullname" . }}
            mountPath: /data
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: py-repo.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "py-repo.fullname" . }} 
  volumeClaimTemplates:
  - metadata:
      name: {{ include "py-repo.fullname" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
      storageClassName: "manual"
