apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "endergy-lib.common.fullname" . }}
  labels:
    {{- include "endergy-lib.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "endergy-lib.common.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "endergy-lib.common.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "endergy-lib.common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "-P", "/auth/.htpasswd", "-a", "update,download,list", "/data/packages" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pypi-data
              mountPath: /data
            - name: htpasswd-file
              mountPath: /auth/.htpasswd
              subPath: .htpasswd
      volumes:
        - name: htpasswd-file
          configMap:
            name: {{ include "endergy-lib.common.fullname" . | quote}}
  volumeClaimTemplates:
    - metadata:
        name: pypi-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
