# Default values for rmq-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jaredhanson11/summn-email-engine
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

# existingSecret, holds secrets for deployment.
#   Make sure all secrets defined in `.Values.secret`
#   are defined in the existing secret
existingSecret: ""
# secret, defines all secret values that need to be set
#   if `.Values.existingSecret` is not set, then use the values
#   from set in this dictionary
secret: {}
# mountedSecrets, mapping of file -> directory
#   describing where secrets should be mapped to
#   within the deployment. the key (aka filename)
#   must be defined in the existingSecret
# ex: "file-name.pem": "/keys/" means the key "file-name.pem"
#   in the existingSecret will be located at /keys/file-name.pem
mountedSecrets: {}
# config, values set as environemnt variables
#   Some common values to be set:
config: {}

dbConnection:
  shouldConnect: false
  prefix: "postgresql://"
  passwordSecret:
    secretName: postgres-secrets
    keyName: postgresql-password
  user: postgres
  port: 5432
  host: postgresql.common
  name: summn_development

resources: {}
