{{- if not .Values.name -}}
{{- fail "Name is a required values" -}}
{{- else if not .Values.path -}}
{{- fail "Path is a required values" -}}
{{- else if not .Values.size -}}
{{- fail "Size is a required values" -}}
{{- end -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.path }}"